// internal/chatbot/service.go
package chatbot

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	
	"smart-health-monitor-go/internal/metrics"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type ChatbotService struct {
	db *mongo.Database
}

func NewChatbotService(db *mongo.Database) *ChatbotService {
	return &ChatbotService{db: db}
}

func (s *ChatbotService) Ask(ctx context.Context, userID string, message string) (string, error) {
	objID, err := primitive.ObjectIDFromHex(userID)
	if err != nil {
    	return "", fmt.Errorf("invalid userID: %w", err)
	}

	// Fetch user
	var user User
	if err := s.db.Collection("users").FindOne(ctx, bson.M{"_id": objID}).Decode(&user); err != nil {
		return "", fmt.Errorf("user not found: %w", err)
	}

	// Fetch latest metrics
	var metricsData metrics.Metric
	_ = s.db.Collection("metrics").FindOne(ctx, bson.M{"userId": userID}).Decode(&metricsData)

	sexStr := "Unknown"
	switch metricsData.Sex {
	case 0:
		sexStr = "Female"
	case 1:
		sexStr = "Male"
	}

	// Build user info
	userInfo := fmt.Sprintf("FirstName: %s\nLastName: %s\n", user.FirstName, user.LastName)
	if metricsData.BMI != 0 {
		userInfo += fmt.Sprintf(
			"Age: %d\nSex: %s\nBMI: %.2f\nBlood Pressure: %.2f\nInsulin: %.2f\nGlucose: %.2f\nCholesterol: %.2f\nSkin Thickness: %.2f\nDiabetes Pedigree: %.2f\nPregnancies: %d\nSmoking Status: %s\nWork Type: %s\nResidence Type: %s\nHypertension: %d\nHeart Disease: %d\nChest Pain Type: %d\nResting ECG: %d\nMax Heart Rate: %.2f\nExercise Induced Angina: %d\nOldpeak: %.2f\nST Segment: %d\nMajor Vessels: %d\nThalassemia: %d\n\nDiabetes Prediction: %s (%.2f)\nHeart Prediction: %s (%.2f)\nStroke Prediction: %s (%.2f)\n",
			metricsData.Age, sexStr, metricsData.BMI,
			metricsData.BloodPressure, metricsData.Insulin,	metricsData.Glucose,
			metricsData.Cholesterol, metricsData.SkinThickness,	metricsData.DiabetesPedigree,
			metricsData.Pregnancies, metricsData.SmokingStatus,	metricsData.WorkType,
			metricsData.ResidenceType, metricsData.Hypertension, metricsData.HeartDisease,
			metricsData.ChestPainType, metricsData.RestingECG, metricsData.MaxHeartRate,
			metricsData.ExerciseInducedAng, metricsData.Oldpeak, metricsData.STSegment,
			metricsData.MajorVessels, metricsData.Thalassemia,
			// Predictions
			metricsData.DiabetesPrediction, metricsData.DiabetesProbability,
			metricsData.HeartPrediction, metricsData.HeartProbability,
			metricsData.StrokePrediction, metricsData.StrokeProbability,
		)
	} else {
		userInfo += "Health metrics not found.\n"
	}

	// Build prompt
	systemPrompt := `You are HealthBot, an intelligent assistant for health advice.
					Provide personalized answers using any available user health info. 
					Health info is generated by Machine Learning models using user's input.
					Do not repeat user data unless needed.`

	chatPrompt := []map[string]string{
		{"role": "system", "content": systemPrompt},
		{"role": "user", "content": fmt.Sprintf("%s\n\nQuestion: %s", userInfo, message)},
	}

	// Call OpenRouter API
	payload := map[string]any{
		"model":    "mistralai/mistral-7b-instruct",
		"messages": chatPrompt,
	}
	body, _ := json.Marshal(payload)

	req, _ := http.NewRequest("POST", "https://openrouter.ai/api/v1/chat/completions", bytes.NewBuffer(body))
	req.Header.Set("Authorization", "Bearer "+os.Getenv("OPENROUTER_API_KEY"))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("HTTP-Referer", "http://localhost:3001")
	req.Header.Set("X-Title", "Smart Health Monitor Chatbot")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("error calling OpenRouter: %w", err)
	}
	defer resp.Body.Close()

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", fmt.Errorf("error parsing response: %w", err)
	}

	if len(result.Choices) == 0 {
		return "No response", nil
	}
	
	return result.Choices[0].Message.Content, nil
}
